defaults:
  - _self_
  - datamodule
  - model

# ここに Trainer 共通パラメータなど
trainer:
  max_epochs : 50
  precision  : 16         # 自動で fp32⇄fp16 を切り替えたいなら  "bf16|16|32|64"
  devices    : 1          # hydra では CLI 上書きも簡単
  accelerator: auto
  log_every_n_steps: 10